### ISSUE TITLE
Using Invalid Email Address for Sending invitation 

### ISSUE THREAD

**Issue by TyronIsDemate** [incrementtechnologies/project_rx_mobile#26]
Case: Invalid Email Address is added to the table of the emails that have been invited
![2020-09-14 (1)](https://user-images.githubusercontent.com/54088760/93158257-5c7dc200-f73e-11ea-8dbb-64286321c106.jpg)

**Comment by kennCK** [comment]
@TyronIsDemate that's a valid email address as it follows the standard..  except for no @ and domain.
