### ISSUE TITLE
Shops in Customer Mobile( Issue in new update)

### ISSUE THREAD

**Issue by TyronIsDemate** [incrementtechnologies/project_rx_mobile#35]
![2020-09-27](https://user-images.githubusercontent.com/54088760/94386540-82fa1f00-017a-11eb-82a9-22ebea98efbd.jpg)
There are no Shops found after clicking Shops in the Homepage. @keyrwinz

**Comment by kennCK** [comment]
@TyronIsDemate @keyrwinz this is resolved.
